name: action-tools
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pytest
  - python-dotenv
  - python-semantic-release
  - toml==0.10.2
  - PyGithub
  - docker-py
  - pip
  - pip:
      - -e .