name: Review Pull Request

on:
  pull_request_target:
    types: [ opened, synchronize, edited, labeled ]
    branches:
      - main

permissions:
  pull-requests: write

# Use concurrency to ensure that only one instance of this workflow is running at a time
concurrency:
  group: pr-lint-checker-${{ github.sha }}
  cancel-in-progress: true

jobs:
  pr-lint-checker:
    uses: ./.github/workflows/tool-pr-linter.yaml
    with:
      python-version: 3.11
    secrets:
      SOURCE_KEY: ${{ secrets.SOURCE_KEY }}

  python-review:
    uses: ./.github/workflows/tool-python-review.yaml
    with:
      python-version: 3.11
    secrets:
      CONDA_API_KEY: ${{ secrets.CONDA_API_KEY }}
      PIP_API_KEY: ${{ secrets.PIP_API_KEY }}

  pr-review-summary:
    name: Python Check Pull Request
    needs: [ pr-lint-checker, pip-conda-checker, pr-pylint ]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install toml==0.10.2

      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Review linting results and create body for comment
        id: comment_body  # Set an ID for this step to reference its outputs
        shell: python
        run: |
          import os
          import base64
          
          def set_output(name, value, encode_it=False):
            if encode_it:
              value = base64.b64encode(value.encode('utf-8')).decode('utf-8')
            with open(os.environ['GITHUB_OUTPUT'], 'a') as fh:
                print(f'{name}={value}', file=fh)
          
          # PR lint results
          has_source_key_str = '${{ needs.pr-lint-checker.outputs.has_source_key_secret }}'
          check_pr_title_str = '${{ needs.pr-lint-checker.outputs.check-pr-title }}'
          check_release_label_str = '${{ needs.pr-lint-checker.outputs.check-release-label }}'
          
          print(f"{has_source_key_str=} {check_pr_title_str=} {check_release_label_str=}")
          
          # Convert the string values to booleans
          has_source_key = has_source_key_str.lower() != 'false'
          check_pr_title = check_pr_title_str.lower() != 'false'
          check_release_label = check_release_label_str.lower() != 'false'
          
          all_checks = [has_source_key, check_pr_title, check_release_label, pylint_result, isort_result, black_result, ruff_result]
          # check if all_checks are true
          if all(all_checks):
            body = "👋 Hi there! I have checked your PR and found no issues. Thanks for your contribution!\n"
            set_output('LINT_OK', 'true')
          else:
            body = "👋 Hi there! I have checked your PR and found the following:\n\n"
            set_output('LINT_OK', 'false')
          
          # PR linting issues
          if all([has_source_key, check_pr_title, check_release_label]) is False:
            body += "\nPR Linting Issues:\n"
          
          if check_pr_title is False:
            body += "\n * ❌ You need to start PR title with fix: feat: fix!: feat!: chore:"
          
          if check_release_label is False:
            body += "\n * ❌ You need to add a release label to your PR. Valid labels: release-XXX (auto, patch, minor, major or skip)"
          
          if has_source_key is False:
            body += "\n * ❌ You need to add SOURCE_KEY as a secret to your repo if you want semantic-release to work"
          
          # Set the output
          set_output('body', body, True)
          
          print(os.environ['GITHUB_OUTPUT'])

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const bodyBase64 = '${{ steps.comment_body.outputs.body }}'
            const body = Buffer.from(bodyBase64, 'base64').toString('utf-8')
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            })

      - name: Fail if linting failed
        if: steps.comment_body.outputs.LINT_OK == 'false'
        run: exit 1