name: Test action tool

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install package
        run: |
          pip install .
          pip install pytest

      - name: Run tests
        run: |
          pytest .
        working-directory: tests