name: Default Release on push of new tag

# triggered on a tagged release
on:
  workflow_call:
    inputs:
      config_toml_file:
        description: "config file in repo for actions"
        type: string
        required: false
        default: "action_config.toml"
      branch: 
        required: false
        type: string
        description: 'PR Branch'
    secrets:
      SOURCE_KEY:
        required: true
      GITOPS_KEY:
        required: false
      CONTAINER_REGISTRY_URL:
        required: false
      CONTAINER_REGISTRY_USERNAME:
        required: false
      CONTAINER_REGISTRY_PASSWORD:
        required: false
      

permissions:
  id-token: write
  contents: write

jobs:
  interpret_tag:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.interpret_tag.outputs.tagged_release }}
      tag_branch: ${{ steps.interpret_tag.outputs.tag_branch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Read and output tag (remove 'v' prefix)
        id: interpret_tag
        shell: python
        run: |
          import os
          
          def set_output(name, value):
            with open(os.environ['GITHUB_OUTPUT'], 'a') as fh:
                print(f'{name}={value}', file=fh)
          
          tag_branch = os.getenv('GITHUB_REF').split('/')[-1] 

          tag = os.getenv('GITHUB_REF').split('/')[-1]
          if tag.startswith('v'):
              tag = tag[1:]
          
          print(f"{tag=}")
          print(f"{tag_branch=}")
          set_output('tagged_release', tag)
          set_output('tag_branch', tag_branch)

  load-config:
    uses: ./.github/workflows/tool-load-config.yaml
    needs: interpret_tag
    with: 
      branch: ${{ needs.interpret_tag.outputs.tag_branch }}
  
  release_docker:
    needs: [ load-config, interpret_tag ]
    if: ${{ needs.load-config.outputs.docker_enabled == 'true' }}
    uses: ./.github/workflows/tool-release-docker.yaml
    with:
      push_docker: 'true'
      docker_matrix: ${{ needs.load-config.outputs.docker_matrix }}
      docker_tag_override: ${{ needs.interpret_tag.outputs.version }}
    secrets:
      CONTAINER_REGISTRY_URL: ${{ secrets.CONTAINER_REGISTRY_URL }}
      CONTAINER_REGISTRY_USERNAME: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
      CONTAINER_REGISTRY_PASSWORD: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

  release_gitops:
    needs: [ load-config, interpret_tag, release_docker ]
    if: ${{ needs.load-config.outputs.gitops_enabled == 'true' }}
    uses: ./.github/workflows/tool-release-gitops-update.yaml
    with:
      push_commit: 'true'
      docker_matrix: ${{ needs.load-config.outputs.docker_matrix }}
      gitops_matrix: ${{ needs.load-config.outputs.gitops_matrix }}
      release_tag_override: ${{ needs.interpret_tag.outputs.version }}
    secrets:
      CONTAINER_REGISTRY_URL: ${{ secrets.CONTAINER_REGISTRY_URL }}
      GITOPS_KEY: ${{ secrets.GITOPS_KEY }}