name: Review Pull Request

on:
  pull_request_target:
    types: [ opened, synchronize, edited, labeled, unlabeled ]
    branches:
      - main
      - develop

permissions:
  pull-requests: write
  contents: write

# Use concurrency to ensure that only one instance of this workflow is running at a time
concurrency:
  group: pr-lint-checker-${{ github.sha }}
  cancel-in-progress: true

jobs:
  review:
    uses: ./.github/workflows/default-tool-pr-review.yaml
    secrets:
      SOURCE_KEY: ${{ secrets.SOURCE_KEY }}
      CONTAINER_REGISTRY_URL: ${{ secrets.CONTAINER_REGISTRY_URL }}
      CONTAINER_REGISTRY_USERNAME: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
      CONTAINER_REGISTRY_PASSWORD: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
      GITOPS_KEY: ${{ secrets.GITOPS_KEY }}