name: tool-generate-semantic-version
on:
  workflow_call:
    inputs:
      python_version:
        description: "Python version"
        type: string
        required: false
        default: "3.11"
      config_toml_file:
        description: "config file in repo for actions"
        type: string
        required: false
        default: "action_config.toml"
      python_semantic_release_pkg:
        description: "python-semantic-release pkg to use"
        type: string
        required: false
        default: "8.5.1"
      release_override:
        description: "if set this will override semantic release and labels used"
        type: string
        required: false
        default: ""
      tool_repo:
        description: "Tool repository"
        type: string
        required: true
      tool_branch:
        description: "Tool branch"
        type: string
        required: true
    secrets:
      SOURCE_KEY:
        required: false

permissions:
  id-token: write
  contents: write
  pull-requests: read

env:
  GITHUB_REPOSITORY: ${{ github.repository }}
  GITHUB_URL: ${{ github.server_url }}
  PR_NUMBER: ${{ github.event.pull_request.number }}
  tool_repo: ${{ inputs.tool_repo }}
  tool_branch: ${{ inputs.tool_branch }}
  CONFIG_TOML_FILE: ${{ inputs.config_toml_file }}

jobs:
  eval-release:
    runs-on: ubuntu-latest
    outputs:
      should_make_a_release: ${{ steps.evaluate-release.outputs.should_make_release }}
      release_label: ${{ steps.evaluate-release.outputs.release_label }}
      pr_title: ${{ steps.evaluate-release.outputs.pr_title }}
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }} # we don't need the PR head sha, we need the base sha to calculate the next version
          fetch-depth: 0

      - name: Checkout Tool
        uses: actions/checkout@v4
        with:
          repository: ${{ env.tool_repo }}
          path: action_tool
          ref: ${{ env.tool_branch }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - run: pip install .
        working-directory: action_tool

      - name: Evaluate Release
        shell: python
        id: evaluate-release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          from action_tool.git_remote_adapter import get_git_remote_adapter
          from action_tool.utils import set_output
          
          git_remote = get_git_remote_adapter()
          if git_remote.should_release():
              set_output("should_make_release", "true")
              rel_label = git_remote.get_pr_release_label()
              pr_title = git_remote.get_pr_title()
              set_output("release_label", rel_label)
              set_output("pr_title", pr_title) 
          else:
              set_output("should_make_release", "false")
  

  generateRelease:
    needs: eval-release
    if: ${{ needs.eval-release.outputs.should_make_a_release == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout git
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{github.ref_name}}
          ssh-key: ${{ secrets.SOURCE_KEY }}

      - name: Checkout Tool
        uses: actions/checkout@v4
        with:
          repository: ${{ env.tool_repo }}
          path: action_tool
          ref: ${{ env.tool_branch }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - run: pip install .
        working-directory: action_tool

      - name: Check PR for any labels suggesting release_override
        shell: python
        env:
          RELEASE_LABEL: ${{ needs.eval-release.outputs.release_label }}
          PR_TITLE: ${{ needs.eval-release.outputs.pr_title }}
          GH_TOKEN: ${{ secrets.SOURCE_KEY }}
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          import os
          from action_tool.git_remote_adapter import GitRemoteRepo
          from action_tool.pr_version_calc import run_semantic_release
          
          rel_label = os.getenv("RELEASE_LABEL")
          pr_title = os.getenv("PR_TITLE")
          config_toml_file = os.getenv("CONFIG_TOML_FILE")
          
          override_label = GitRemoteRepo.release_label_map.get(rel_label)
          if override_label == "":
              override_label = None
              
          run_semantic_release(config_toml_file, pr_title, override_label)
